// Auto-generated by `npm run types` (supabase gen types typescript --local).
// Re-run after schema changes: supabase db reset && npm run types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      affiliate_attributions: {
        Row: {
          affiliated_at: string
          affiliate_id: string
          code: string
          id: string
          subscription_id: string
        }
        Insert: {
          affiliated_at?: string
          affiliate_id: string
          code: string
          id?: string
          subscription_id: string
        }
        Update: {
          affiliated_at?: string
          affiliate_id?: string
          code?: string
          id?: string
          subscription_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "affiliate_attributions_affiliate_id_fkey"
            columns: ["affiliate_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "affiliate_attributions_subscription_id_fkey"
            columns: ["subscription_id"]
            isOneToOne: true
            referencedRelation: "subscriptions"
            referencedColumns: ["id"]
          },
        ]
      }
      affiliate_badges: {
        Row: {
          description: string
          display_name: string
          icon_emoji: string | null
          id: string
          sort_order: number
          threshold_kind: string
          threshold_value: number
        }
        Insert: {
          description: string
          display_name: string
          icon_emoji?: string | null
          id: string
          sort_order: number
          threshold_kind: string
          threshold_value: number
        }
        Update: {
          description?: string
          display_name?: string
          icon_emoji?: string | null
          id?: string
          sort_order?: number
          threshold_kind?: string
          threshold_value?: number
        }
        Relationships: []
      }
      affiliate_links: {
        Row: {
          affiliate_id: string
          app_id: string | null
          code: string
          created_at: string
          id: string
        }
        Insert: {
          affiliate_id: string
          app_id?: string | null
          code: string
          created_at?: string
          id?: string
        }
        Update: {
          affiliate_id?: string
          app_id?: string | null
          code?: string
          created_at?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "affiliate_links_affiliate_id_fkey"
            columns: ["affiliate_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "affiliate_links_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
        ]
      }
      apps: {
        Row: {
          affiliate_commission_bps: number | null
          auth_url: string | null
          category: string | null
          created_at: string
          currency: string
          description: string | null
          first_verified_at: string | null
          id: string
          logo_url: string | null
          min_price_cents: number | null
          name: string
          price_cents: number
          status: Database["public"]["Enums"]["app_status"]
          stripe_price_id: string | null
          stripe_product_id: string | null
          updated_at: string
          vendor_id: string
        }
        Insert: {
          affiliate_commission_bps?: number | null
          auth_url?: string | null
          category?: string | null
          created_at?: string
          currency?: string
          description?: string | null
          first_verified_at?: string | null
          id?: string
          logo_url?: string | null
          min_price_cents?: number | null
          name: string
          price_cents: number
          status?: Database["public"]["Enums"]["app_status"]
          stripe_price_id?: string | null
          stripe_product_id?: string | null
          updated_at?: string
          vendor_id: string
        }
        Update: {
          affiliate_commission_bps?: number | null
          auth_url?: string | null
          category?: string | null
          created_at?: string
          currency?: string
          description?: string | null
          first_verified_at?: string | null
          id?: string
          logo_url?: string | null
          min_price_cents?: number | null
          name?: string
          price_cents?: number
          status?: Database["public"]["Enums"]["app_status"]
          stripe_price_id?: string | null
          stripe_product_id?: string | null
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "apps_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_log: {
        Row: {
          action: string
          actor_id: string | null
          actor_role: string | null
          created_at: string
          entity_id: string | null
          entity_type: string
          id: string
          metadata: Json | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          actor_role?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type: string
          id?: string
          metadata?: Json | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          actor_role?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string
          id?: string
          metadata?: Json | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          affiliate_active_mrr_cents: number
          affiliate_avatar_url: string | null
          affiliate_bio: string | null
          affiliate_lifetime_mrr_cents: number
          charges_enabled: boolean
          created_at: string
          display_name: string | null
          id: string
          payouts_enabled: boolean
          role: Database["public"]["Enums"]["user_role"]
          slug: string | null
          stripe_account_id: string | null
          stripe_customer_id: string | null
          updated_at: string
        }
        Insert: {
          affiliate_active_mrr_cents?: number
          affiliate_avatar_url?: string | null
          affiliate_bio?: string | null
          affiliate_lifetime_mrr_cents?: number
          charges_enabled?: boolean
          created_at?: string
          display_name?: string | null
          id: string
          payouts_enabled?: boolean
          role?: Database["public"]["Enums"]["user_role"]
          slug?: string | null
          stripe_account_id?: string | null
          stripe_customer_id?: string | null
          updated_at?: string
        }
        Update: {
          affiliate_active_mrr_cents?: number
          affiliate_avatar_url?: string | null
          affiliate_bio?: string | null
          affiliate_lifetime_mrr_cents?: number
          charges_enabled?: boolean
          created_at?: string
          display_name?: string | null
          id?: string
          payouts_enabled?: boolean
          role?: Database["public"]["Enums"]["user_role"]
          slug?: string | null
          stripe_account_id?: string | null
          stripe_customer_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      reseller_offers: {
        Row: {
          app_id: string
          created_at: string
          id: string
          reseller_id: string
          sell_price_cents: number
          slug: string
          status: Database["public"]["Enums"]["reseller_offer_status"]
          stripe_price_id: string | null
          updated_at: string
          vendor_floor_snapshot_cents: number
        }
        Insert: {
          app_id: string
          created_at?: string
          id?: string
          reseller_id: string
          sell_price_cents: number
          slug: string
          status?: Database["public"]["Enums"]["reseller_offer_status"]
          stripe_price_id?: string | null
          updated_at?: string
          vendor_floor_snapshot_cents?: number
        }
        Update: {
          app_id?: string
          created_at?: string
          id?: string
          reseller_id?: string
          sell_price_cents?: number
          slug?: string
          status?: Database["public"]["Enums"]["reseller_offer_status"]
          stripe_price_id?: string | null
          updated_at?: string
          vendor_floor_snapshot_cents?: number
        }
        Relationships: [
          {
            foreignKeyName: "reseller_offers_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reseller_offers_reseller_id_fkey"
            columns: ["reseller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      reseller_subscriptions: {
        Row: {
          cancel_at_period_end: boolean
          canceled_at: string | null
          created_at: string
          current_period_end: string
          id: string
          reseller_id: string
          status: Database["public"]["Enums"]["subscription_status"]
          stripe_subscription_id: string
          updated_at: string
        }
        Insert: {
          cancel_at_period_end?: boolean
          canceled_at?: string | null
          created_at?: string
          current_period_end: string
          id?: string
          reseller_id: string
          status: Database["public"]["Enums"]["subscription_status"]
          stripe_subscription_id: string
          updated_at?: string
        }
        Update: {
          cancel_at_period_end?: boolean
          canceled_at?: string | null
          created_at?: string
          current_period_end?: string
          id?: string
          reseller_id?: string
          status?: Database["public"]["Enums"]["subscription_status"]
          stripe_subscription_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "reseller_subscriptions_reseller_id_fkey"
            columns: ["reseller_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          affiliate_commission_snapshot_bps: number | null
          affiliate_id: string | null
          anon_user_id: string
          app_id: string
          buyer_id: string
          cancel_at_period_end: boolean
          canceled_at: string | null
          created_at: string
          currency: string
          current_period_end: string
          id: string
          pause_started_at: string | null
          paused_until: string | null
          price_cents: number
          reseller_id: string | null
          reseller_offer_id: string | null
          status: Database["public"]["Enums"]["subscription_status"]
          stripe_customer_id: string
          stripe_subscription_id: string
          updated_at: string
          vendor_floor_snapshot_cents: number | null
        }
        Insert: {
          affiliate_commission_snapshot_bps?: number | null
          affiliate_id?: string | null
          anon_user_id: string
          app_id: string
          buyer_id: string
          cancel_at_period_end?: boolean
          canceled_at?: string | null
          created_at?: string
          currency?: string
          current_period_end: string
          id?: string
          pause_started_at?: string | null
          paused_until?: string | null
          price_cents: number
          reseller_id?: string | null
          reseller_offer_id?: string | null
          status: Database["public"]["Enums"]["subscription_status"]
          stripe_customer_id: string
          stripe_subscription_id: string
          updated_at?: string
          vendor_floor_snapshot_cents?: number | null
        }
        Update: {
          affiliate_commission_snapshot_bps?: number | null
          affiliate_id?: string | null
          anon_user_id?: string
          app_id?: string
          buyer_id?: string
          cancel_at_period_end?: boolean
          canceled_at?: string | null
          created_at?: string
          currency?: string
          current_period_end?: string
          id?: string
          pause_started_at?: string | null
          paused_until?: string | null
          price_cents?: number
          reseller_id?: string | null
          reseller_offer_id?: string | null
          status?: Database["public"]["Enums"]["subscription_status"]
          stripe_customer_id?: string
          stripe_subscription_id?: string
          updated_at?: string
          vendor_floor_snapshot_cents?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_affiliate_id_fkey"
            columns: ["affiliate_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_buyer_id_fkey"
            columns: ["buyer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_reseller_id_fkey"
            columns: ["reseller_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_reseller_offer_fk"
            columns: ["reseller_offer_id"]
            isOneToOne: false
            referencedRelation: "reseller_offers"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_revenue_events: {
        Row: {
          amount_cents: number
          net_amount_cents: number
          app_id: string | null
          created_at: string
          id: string
          is_reseller_sale: boolean
          occurred_at: string
          stripe_charge_id: string | null
          stripe_event_id: string | null
          stripe_invoice_id: string | null
          subscription_id: string | null
          vendor_id: string
        }
        Insert: {
          amount_cents: number
          net_amount_cents: number
          app_id?: string | null
          created_at?: string
          id?: string
          is_reseller_sale?: boolean
          occurred_at?: string
          stripe_charge_id?: string | null
          stripe_event_id?: string | null
          stripe_invoice_id?: string | null
          subscription_id?: string | null
          vendor_id: string
        }
        Update: {
          amount_cents?: number
          net_amount_cents?: number
          app_id?: string | null
          created_at?: string
          id?: string
          is_reseller_sale?: boolean
          occurred_at?: string
          stripe_charge_id?: string | null
          stripe_event_id?: string | null
          stripe_invoice_id?: string | null
          subscription_id?: string | null
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_revenue_events_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_revenue_events_app_id_fkey"
            columns: ["app_id"]
            isOneToOne: false
            referencedRelation: "apps"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vendor_revenue_events_subscription_id_fkey"
            columns: ["subscription_id"]
            isOneToOne: false
            referencedRelation: "subscriptions"
            referencedColumns: ["id"]
          },
        ]
      }
      vendor_billing: {
        Row: {
          computed_at: string
          created_at: string
          cut_bps: number
          gross_revenue_cents: number
          id: string
          period_end: string
          period_start: string
          tier: number
          updated_at: string
          vendor_id: string
        }
        Insert: {
          computed_at?: string
          created_at?: string
          cut_bps: number
          gross_revenue_cents: number
          id?: string
          period_end: string
          period_start: string
          tier: number
          updated_at?: string
          vendor_id: string
        }
        Update: {
          computed_at?: string
          created_at?: string
          cut_bps?: number
          gross_revenue_cents?: number
          id?: string
          period_end?: string
          period_start?: string
          tier?: number
          updated_at?: string
          vendor_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "vendor_billing_vendor_id_fkey"
            columns: ["vendor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      webhook_events: {
        Row: {
          error: string | null
          id: string
          payload: Json
          processed_at: string | null
          received_at: string
          status: string
          type: string
        }
        Insert: {
          error?: string | null
          id: string
          payload: Json
          processed_at?: string | null
          received_at?: string
          status?: string
          type: string
        }
        Update: {
          error?: string | null
          id?: string
          payload?: Json
          processed_at?: string | null
          received_at?: string
          status?: string
          type?: string
        }
        Relationships: []
      }
    }
    Views: {
      affiliate_leaderboard: {
        Row: {
          id: string
          slug: string
          display_name: string | null
          affiliate_avatar_url: string | null
          affiliate_active_mrr_cents: number
          affiliate_lifetime_mrr_cents: number
          tenure_days: number
          active_rank: number
          lifetime_rank: number
        }
        Relationships: []
      }
    }
    Functions: {
      affiliate_earned_badges: {
        Args: { p_affiliate_id: string }
        Returns: {
          id: string
          display_name: string
          description: string
          threshold_kind: string
          threshold_value: number
          icon_emoji: string | null
          sort_order: number
        }[]
      }
      increment_affiliate_lifetime_mrr: {
        Args: { p_affiliate_id: string; p_amount_cents: number }
        Returns: undefined
      }
      vendor_cohort_retention: {
        Args: { p_vendor_id: string }
        Returns: {
          cohort_month: string
          month_offset: number
          retained_count: number
          cohort_size: number
        }[]
      }
      get_marketplace_app: {
        Args: { p_id: string }
        Returns: {
          id: string
          name: string
          description: string | null
          category: string | null
          price_cents: number
          currency: string
          auth_url: string | null
          vendor_name: string | null
        }[]
      }
      list_marketplace_apps: {
        Args: {
          p_search?: string | null
          p_category?: string | null
          p_page?: number
          p_page_size?: number
        }
        Returns: {
          id: string
          name: string
          description: string | null
          category: string | null
          price_cents: number
          currency: string
          vendor_name: string | null
          total_count: number
        }[]
      }
      list_marketplace_categories: {
        Args: Record<PropertyKey, never>
        Returns: { category: string }[]
      }
      affiliate_stats: {
        Args: Record<PropertyKey, never>
        Returns: {
          app_id: string
          active_subs: number
          mrr_gross_cents: number
        }[]
      }
      compute_vendor_billing: {
        Args: {
          p_vendor_id: string
          p_period_start: string
          p_period_end: string
        }
        Returns: undefined
      }
      get_current_user_role: {
        Args: Record<PropertyKey, never>
        Returns: Database["public"]["Enums"]["user_role"]
      }
      reseller_sale_stats: {
        Args: Record<PropertyKey, never>
        Returns: {
          app_id: string
          reseller_offer_id: string
          anon_user_id: string
          status: Database["public"]["Enums"]["subscription_status"]
          price_cents: number
          vendor_floor_snapshot_cents: number
          current_period_end: string
        }[]
      }
      vendor_subscription_stats: {
        Args: Record<PropertyKey, never>
        Returns: {
          app_id: string
          anon_user_id: string
          status: Database["public"]["Enums"]["subscription_status"]
          price_cents: number
          current_period_end: string
        }[]
      }
    }
    Enums: {
      app_status: "pending" | "approved" | "rejected"
      reseller_offer_status: "draft" | "active" | "paused"
      subscription_status:
        | "incomplete"
        | "incomplete_expired"
        | "active"
        | "trialing"
        | "past_due"
        | "unpaid"
        | "canceled"
        | "paused"
      user_role: "admin" | "vendor" | "buyer" | "affiliate" | "reseller"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      app_status: ["pending", "approved", "rejected"],
      reseller_offer_status: ["draft", "active", "paused"],
      subscription_status: [
        "incomplete",
        "incomplete_expired",
        "active",
        "trialing",
        "past_due",
        "unpaid",
        "canceled",
        "paused",
      ],
      user_role: ["admin", "vendor", "buyer", "affiliate", "reseller"],
    },
  },
} as const
